### ISSUE TITLE
Name-spacing fixes needed for SilverStripe v4.0

### ISSUE THREAD

**Issue by jaydenseric** [burnbright/silverstripe-hasonefield#5]
This module is incompatible with the current unreleased SilverStripe v4.0 due to new name-spacing requirements and breaks horribly.

Running [silverstripe-upgrader](https://github.com/silverstripe/silverstripe-upgrader) on it seems to fix all name-spacing issues.

**Comment by bummzack** [comment]
I fail to understand how this was merged without creating a separate branch/release first?
@jedateach could you tag a release before this PR was merged, so people can use the module with SilverStripe 3.x as well? Ideally, composer.json would also be updated to reflect what Version of SilverStripe this is compatible with.

**Comment by jedateach** [comment]
@bummzack is there a new owner I can hand this over to?

**Comment by bummzack** [comment]
@jedateach Did you contact somebody at SilverStripe Ltd? I think they might know better

**Comment by jedateach** [comment]
I did: https://silverstripe.uservoice.com/forums/251266-new-features/suggestions/20319142-help-to-pass-on-unmaintained-modules
